version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /apps/console-web
    schedule:
      interval: weekly
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /apps/desktop
    schedule:
      interval: weekly
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /apps/mobile-web
    schedule:
      interval: weekly
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
