import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import test from 'node:test';

import { hasProviderEvidence } from './scenarios/discovery-reuse-horizon.js';

const SOURCE_MARKER = 'PROOF_RELEASE_QUEUE:LOCAL_ONLY';
const ITEM_ID = 'proof-release-1';
const ITEM_TITLE = 'Review the Clementine 4 release proof';
const REPORT_071811 = 'proof-reports/2026-08-09T07-18-11-864Z-a1c5b22181f8.json';
const REPORT_105941 = 'proof-reports/2026-08-09T10-59-41-287Z-e1b53ee9eba4.json';
const REPORT_112306 = 'proof-reports/2026-08-09T11-23-06-483Z-2ebd4084d4df.json';
const REPORT_113945 = 'proof-reports/2026-08-09T11-39-45-261Z-2d5b144de754.json';
const REPORT_124825 = 'proof-reports/2026-08-09T12-48-25-151Z-6aaac2c630e9.json';
const REPORT_130343 = 'proof-reports/2026-08-09T13-03-43-747Z-82e647085732.json';

const lines = (...value: string[]): string => value.join('\n');
const code = (value: string): string => String.fromCharCode(96) + value + String.fromCharCode(96);
const quoted = (value: string): string => '"' + value + '"';
const hardBreak = (value: string): string => value + '  ';

interface RetainedVoice {
  name: string;
  report: string;
  brain: 'claude' | 'codex' | 'glm';
  step: 'cold_connected_read' | 'learned_connected_reuse' | 'restart_resume_connected_read';
  revision: 1 | 2;
  status: 'open' | 'done';
  sha256: string;
  publicText: string;
}

const RETAINED_VOICES: RetainedVoice[] = [
  {
    name: '071811-claude-cold',
    report: REPORT_071811,
    brain: 'claude',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: 'bc2b77e3f614234a47658fdba39719397f8d78fe046c44b6e82f3b97985a22a9',
    publicText: lines(
      "Here's the proof release queue result:",
      '',
      '- **Source marker:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 1',
      '- **Item ID:** proof-release-1',
      '- **Title:** Review the Clementine 4 release proof',
      '- **Status:** open',
    ),
  },
  {
    name: '071811-claude-reuse',
    report: REPORT_071811,
    brain: 'claude',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: 'a38527fc4164e09a7278528dcea9be00dbd0d785964b99fa3f763445769f8bf4',
    publicText: lines(
      'Refreshed proof release queue:',
      '',
      '- **Source marker:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 1',
      '- **Item ID:** proof-release-1',
      '- **Title:** Review the Clementine 4 release proof',
      '- **Status:** open',
      '',
      'No changes since last check.',
    ),
  },
  {
    name: '071811-claude-restart',
    report: REPORT_071811,
    brain: 'claude',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: 'b291ccd67ccd94587ca95c248d35093711255fa438d32942e9f90b3034d35a1f',
    publicText: lines(
      'Refreshed proof release queue — it changed since last check:',
      '',
      '- **Source marker:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 2 (was 1)',
      '- **Item ID:** proof-release-1',
      '- **Title:** Review the Clementine 4 release proof',
      '- **Status:** done (was open)',
    ),
  },
  {
    name: '071811-codex-cold',
    report: REPORT_071811,
    brain: 'codex',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: 'b58baae8e389b41c4cbb3e643f16d9d1cd55d7d7642f647325b912611b305706',
    publicText: lines(
      hardBreak('Source marker: ' + code(SOURCE_MARKER)),
      hardBreak('Revision: 1'),
      hardBreak('Item ID: ' + code(ITEM_ID)),
      hardBreak('Title: ' + ITEM_TITLE),
      'Status: Open',
    ),
  },
  {
    name: '071811-codex-reuse',
    report: REPORT_071811,
    brain: 'codex',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: 'b58baae8e389b41c4cbb3e643f16d9d1cd55d7d7642f647325b912611b305706',
    publicText: lines(
      hardBreak('Source marker: ' + code(SOURCE_MARKER)),
      hardBreak('Revision: 1'),
      hardBreak('Item ID: ' + code(ITEM_ID)),
      hardBreak('Title: ' + ITEM_TITLE),
      'Status: Open',
    ),
  },
  {
    name: '071811-codex-restart',
    report: REPORT_071811,
    brain: 'codex',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: 'f8cf33094f3bc2e21d8736a7fc781565bccc288509edfbd1694acd051fb396fe',
    publicText: lines(
      hardBreak('Source marker: ' + code(SOURCE_MARKER)),
      hardBreak('Revision: 2'),
      hardBreak('Item ID: ' + code(ITEM_ID)),
      hardBreak('Title: ' + ITEM_TITLE),
      'Status: Done',
    ),
  },
  {
    name: '071811-glm-cold',
    report: REPORT_071811,
    brain: 'glm',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: '96224126d6feb02e5fd474d9bd55b89f95df4ed00e8d6576bacf0e7eee6081ae',
    publicText: lines(
      "Here's the current proof release queue (1 item):",
      '',
      '| Source marker | Revision | Item ID | Title | Status |',
      '|---|---|---|---|---|',
      '| PROOF_RELEASE_QUEUE:LOCAL_ONLY | 1 | proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      'One open item in the queue, at revision 1.',
    ),
  },
  {
    name: '071811-glm-reuse',
    report: REPORT_071811,
    brain: 'glm',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: '9933c9fd5d5eccfab98af58b2cdccb2d067de422d6bf3e6da03bf297bd01400c',
    publicText: lines(
      'Queue refreshed — unchanged from the last pull:',
      '',
      '| Source marker | Revision | Item ID | Title | Status |',
      '|---|---|---|---|---|',
      '| PROOF_RELEASE_QUEUE:LOCAL_ONLY | 1 | proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      'Still one open item, at revision 1.',
    ),
  },
  {
    name: '071811-glm-restart',
    report: REPORT_071811,
    brain: 'glm',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: 'eaab2ac9c2b3c584382efe63b10ce18814c225d837cbe04be3aa606856ebb88b',
    publicText: lines(
      "Queue refreshed — there's been a change since the last pull:",
      '',
      '| Source marker | Revision | Item ID | Title | Status |',
      '|---|---|---|---|---|',
      '| PROOF_RELEASE_QUEUE:LOCAL_ONLY | 2 | proof-release-1 | Review the Clementine 4 release proof | done |',
      '',
      "The queue advanced from revision 1 to revision 2, and the single item's status flipped from **open** to **done**.",
    ),
  },
  {
    name: '105941-claude-cold',
    report: REPORT_105941,
    brain: 'claude',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: 'db16250faf1c4dec34cf43f8a31af46491e4faf9200fbfe2aa4b16eac77071e6',
    publicText: lines(
      "Here's the current proof release queue:",
      '',
      '- **Source:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 1',
      '- **Item:** ' + code(ITEM_ID) + ' — ' + quoted(ITEM_TITLE) + ' — status: **open**',
    ),
  },
  {
    name: '105941-claude-reuse',
    report: REPORT_105941,
    brain: 'claude',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: 'c99c6bc3ca331c4ee00ba61f2fc1b3ff68c079c19978198c5d0dc0c2a1354458',
    publicText: lines(
      'Refreshed proof release queue:',
      '',
      '- **Source:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 1',
      '- **Item:** ' + code(ITEM_ID) + ' — ' + quoted(ITEM_TITLE) + ' — status: **open**',
      '',
      'Unchanged from before.',
    ),
  },
  {
    name: '105941-claude-restart',
    report: REPORT_105941,
    brain: 'claude',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: 'a03c9bd75648d1caf565b186b395934f59f7d1e7e2283eded4b1dc3e89b5a6f0',
    publicText: lines(
      'Refreshed proof release queue:',
      '',
      '- **Source:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 2',
      '- **Item:** ' + code(ITEM_ID) + ' — ' + quoted(ITEM_TITLE) + ' — status: **done**',
      '',
      "It's advanced since last check — status moved from open to done, and the revision bumped to 2.",
    ),
  },
  {
    name: '105941-codex-cold',
    report: REPORT_105941,
    brain: 'codex',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: '4aa2c50944f97fd017d2cadf263a88536812384e7c5c64f3c5e1561aeee03a46',
    publicText: lines(
      '- Source marker: ' + code(SOURCE_MARKER),
      '- Revision: 1',
      '- Item ID: ' + code(ITEM_ID),
      '- Title: ' + ITEM_TITLE,
      '- Status: Open',
    ),
  },
  {
    name: '105941-codex-reuse',
    report: REPORT_105941,
    brain: 'codex',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: '4aa2c50944f97fd017d2cadf263a88536812384e7c5c64f3c5e1561aeee03a46',
    publicText: lines(
      '- Source marker: ' + code(SOURCE_MARKER),
      '- Revision: 1',
      '- Item ID: ' + code(ITEM_ID),
      '- Title: ' + ITEM_TITLE,
      '- Status: Open',
    ),
  },
  {
    name: '105941-codex-restart',
    report: REPORT_105941,
    brain: 'codex',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: '431fa1ed9641df54eb60d13861abd0b58b918a368ffb76fa005c4e49b3201886',
    publicText: lines(
      '- Source marker: ' + code(SOURCE_MARKER),
      '- Revision: 2',
      '- Item ID: ' + code(ITEM_ID),
      '- Title: ' + ITEM_TITLE,
      '- Status: Done',
    ),
  },
  {
    name: '105941-glm-cold',
    report: REPORT_105941,
    brain: 'glm',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: 'cfccccd3e56178ddd66e49e117f9c77538cf574cfadf00900cc8d71871bfdcdc',
    publicText: lines(
      'Here are the current items in the proof release queue (source marker ' + code(SOURCE_MARKER) + ', revision 1):',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      "Total: 1 item. Read fetched fresh via the authenticated Composio CLI's local proof provider (no account selected).",
    ),
  },
  {
    name: '105941-glm-reuse',
    report: REPORT_105941,
    brain: 'glm',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: 'ea98d0eafd3dc94ba886502089eb16d1534de72b4c46cef91c0835f7c7db5a72',
    publicText: lines(
      'Fresh read of the proof release queue (source marker ' + code(SOURCE_MARKER) + ', revision 1):',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      'Still 1 item, unchanged since the last read — same source and revision via the local proof provider.',
    ),
  },
  {
    name: '105941-glm-restart',
    report: REPORT_105941,
    brain: 'glm',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: '85d97b5199bde80b204fee87cef91f56183d5549ffa459230ed4f574ad17e613',
    publicText: lines(
      'Fresh read of the proof release queue (source marker ' + code(SOURCE_MARKER) + ', now at **revision 2**):',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | done |',
      '',
      'Still 1 item, but its status flipped from ' + code('open') + ' → ' + code('done') + ' and the revision advanced from 1 to 2 — the provider state changed since the last read.',
    ),
  },
  {
    name: '112306-glm-cold',
    report: REPORT_112306,
    brain: 'glm',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: '413385438c430bc5b9fbc32b20e4c9d1819e01a43435d4739238d9ba6df38fa5',
    publicText: lines(
      "Here's the current proof release queue:",
      '',
      '- **Source marker:** ' + code(SOURCE_MARKER),
      '- **Revision:** 1',
      '- **Total items:** 1',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      'Retrieved via ' + code('PROOF_LIST_TASKS') + ' on the local proof provider; no connected account was selected.',
    ),
  },
  {
    name: '112306-glm-reuse',
    report: REPORT_112306,
    brain: 'glm',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: '565ed2b163f91ff3b1e57c36fffdc4aff0ce64dfe2d7b61fa669eb06195d1e22',
    publicText: lines(
      'Refreshed — the queue is unchanged:',
      '',
      '- **Source marker:** ' + code(SOURCE_MARKER),
      '- **Revision:** 1',
      '- **Total items:** 1',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | open |',
    ),
  },
  {
    name: '112306-glm-restart',
    report: REPORT_112306,
    brain: 'glm',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: 'f60cd3e376acee7e6f168fc2bc0493cf0174a02d9dfa5dce4e7d0504ebfb4b8b',
    publicText: lines(
      "State has advanced — here's the refreshed queue:",
      '',
      '- **Source marker:** ' + code(SOURCE_MARKER),
      '- **Revision:** 2 (up from 1)',
      '- **Total items:** 1',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | done |',
      '',
      'The only item flipped from **open** to **done** since the last read.',
    ),
  },
  {
    name: '113945-glm-cold',
    report: REPORT_113945,
    brain: 'glm',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: '511b66924f7a4852f754d61c5bd4ca56a4a86c5bb92cc6d104e1a8b6a0b71176',
    publicText: lines(
      'Proof release queue (local provider, revision 1):',
      '',
      '- **proof-release-1** — ' + quoted(ITEM_TITLE) + ' — status: **open**',
      '',
      'Source marker: ' + code(SOURCE_MARKER) + ". That's the only current item.",
    ),
  },
  {
    name: '113945-glm-reuse',
    report: REPORT_113945,
    brain: 'glm',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: '32ef42a9ba5c3454c6b9506d146ad1f6aaa1dc10815aa7a170706b89c988b55e',
    publicText: lines(
      'Proof release queue (local provider, revision 1):',
      '',
      '- **proof-release-1** — ' + quoted(ITEM_TITLE) + ' — status: **open**',
      '',
      'Source marker: ' + code(SOURCE_MARKER) + '. Unchanged since the last read.',
    ),
  },
  {
    name: '113945-glm-restart',
    report: REPORT_113945,
    brain: 'glm',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: '847f98d69d09ac6fcb8a911024b364b50b0de81ec0432300e75698c63ec52ef3',
    publicText: lines(
      'Proof release queue (local provider, revision 2):',
      '',
      '- **proof-release-1** — ' + quoted(ITEM_TITLE) + ' — status: **done**',
      '',
      'Source marker: ' + code(SOURCE_MARKER) + '. State changed since the last read — the item is now done.',
    ),
  },
  {
    name: '124825-glm-cold',
    report: REPORT_124825,
    brain: 'glm',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: '73a61b685c15e97ceb0880cd8bb3edfa10533839166bb34f5f30b9a854a811c6',
    publicText: lines(
      'Proof release queue — current items:',
      '',
      '- **Source marker:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 1',
      '- **Item id:** proof-release-1',
      '- **Title:** Review the Clementine 4 release proof',
      '- **Status:** open',
      '',
      'Total: 1 item.',
    ),
  },
  {
    name: '124825-glm-reuse',
    report: REPORT_124825,
    brain: 'glm',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: 'ca80b5322f7cae39e46ea93e215371ac800d72aa2306d4e3ecb4fefa4a8159d9',
    publicText: lines(
      "Here's the current proof release queue:",
      '',
      '| Field | Value |',
      '|---|---|',
      '| **Source marker** | ' + code(SOURCE_MARKER) + ' |',
      '| **Revision** | 1 |',
      '',
      '**Items (1 total):**',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      'Pulled fresh from the same connected source via the proven capability. One open item in the queue.',
    ),
  },
  {
    name: '124825-glm-restart',
    report: REPORT_124825,
    brain: 'glm',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: '658539ac5b72443956a2f29e9ce32166958705cdb16d3aae5ad56336e6ee11f1',
    publicText: lines(
      'Fresh read complete — the provider state updated:',
      '',
      '| Field | Value |',
      '|---|---|',
      '| **Source marker** | ' + code(SOURCE_MARKER) + ' |',
      '| **Revision** | 2 |',
      '',
      '**Items (1 total):**',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | done |',
      '',
      'The queue advanced from revision 1 → 2, and the single item flipped from **open** to **done**.',
    ),
  },
  {
    name: '130343-glm-cold',
    report: REPORT_130343,
    brain: 'glm',
    step: 'cold_connected_read',
    revision: 1,
    status: 'open',
    sha256: 'd586cbae43a30b06879163f0b56eaa98ff81f44095d8bbcf22d086241ac45665',
    publicText: lines(
      'Proof release queue — current items:',
      '',
      '- **Source marker:** PROOF_RELEASE_QUEUE:LOCAL_ONLY',
      '- **Revision:** 1',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      '1 item total, all open.',
    ),
  },
  {
    name: '130343-glm-reuse',
    report: REPORT_130343,
    brain: 'glm',
    step: 'learned_connected_reuse',
    revision: 1,
    status: 'open',
    sha256: '156facd3ec53aae003d06cf7fbeec028675900bb6865434f7674f101d6e17913',
    publicText: lines(
      'Proof release queue refreshed from the same source:',
      '',
      '- **Source marker:** ' + code(SOURCE_MARKER),
      '- **Revision:** 1',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | open |',
      '',
      '1 item total.',
    ),
  },
  {
    name: '130343-glm-restart',
    report: REPORT_130343,
    brain: 'glm',
    step: 'restart_resume_connected_read',
    revision: 2,
    status: 'done',
    sha256: '427b065e131a6317d5224eda10ab4568aab6b8e6493df67876eda42ce84b2339',
    publicText: lines(
      'Fresh read from the same source:',
      '',
      '- **Source marker:** ' + code(SOURCE_MARKER),
      '- **Revision:** 2',
      '',
      '| Item ID | Title | Status |',
      '|---|---|---|',
      '| proof-release-1 | Review the Clementine 4 release proof | done |',
      '',
      'The item flipped from **open** to **done** since the last read (revision bumped 1 → 2).',
    ),
  },
];

test('all 30 retained Claude, Codex, and GLM read voices remain exact provider evidence', () => {
  assert.equal(RETAINED_VOICES.length, 30);
  for (const fixture of RETAINED_VOICES) {
    const publicBytes = Buffer.from(fixture.publicText, 'utf8');
    const roundTrippedPublicText = publicBytes.toString('utf8');
    assert.equal(
      createHash('sha256').update(publicBytes).digest('hex'),
      fixture.sha256,
      fixture.name + ': hardcoded public bytes drifted from ' + fixture.report,
    );
    assert.deepEqual(
      Buffer.from(roundTrippedPublicText, 'utf8'),
      publicBytes,
      fixture.name + ': public presentation did not remain byte-identical',
    );
    assert.equal(
      hasProviderEvidence(
        roundTrippedPublicText,
        fixture.revision,
        fixture.status,
        fixture.step === 'cold_connected_read'
          ? 'cold'
          : fixture.step === 'learned_connected_reuse'
            ? 'reuse'
            : 'correction',
      ),
      true,
      fixture.name + ': ' + fixture.brain + '/' + fixture.step + ' no longer validates',
    );
  }
});
