/** Known OpenAI-compatible providers — base URL + a sensible worker model. */
export const PROVIDER_PRESETS: { id: string; label: string; baseURL: string; workerModel: string; modelHint: string }[] = [
  { id: 'deepseek', label: 'DeepSeek', baseURL: 'https://api.deepseek.com', workerModel: 'deepseek-chat', modelHint: 'deepseek-chat (fast, non-thinking) is best for worker grunt work. deepseek-reasoner for hard reasoning. (New aliases: deepseek-v4-flash / deepseek-v4-pro.)' },
  { id: 'minimax', label: 'MiniMax', baseURL: 'https://api.minimax.io/v1', workerModel: 'MiniMax-M3', modelHint: 'MiniMax-M3 — current flagship (1M context, multimodal, agentic). Alternatives: MiniMax-M2.7, MiniMax-M2.7-highspeed, MiniMax-M2.' },
  { id: 'together', label: 'Together AI', baseURL: 'https://api.together.ai/v1', workerModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', modelHint: 'Together AI hosts many open models (Llama, DeepSeek, Qwen, Mistral). Click "Browse models" to pull the live catalog, or type ids like meta-llama/Llama-3.3-70B-Instruct-Turbo / deepseek-ai/DeepSeek-V3.' },
  { id: 'glm-coding', label: 'GLM (Z.ai) — Coding Plan', baseURL: 'https://api.z.ai/api/coding/paas/v4', workerModel: 'glm-5.2', modelHint: 'For Z.ai GLM Coding Plan subscribers — uses the dedicated coding endpoint (api/coding/paas/v4), which draws on your plan allowance. Pick THIS if you have a Coding Plan; the plain "GLM (Z.ai)" endpoint ignores it and falls back to standard pay-as-you-go rate limits. Model: glm-5.2 (1M context).' },
  { id: 'glm', label: 'GLM (Z.ai) — Standard API', baseURL: 'https://api.z.ai/api/paas/v4', workerModel: 'glm-5.2', modelHint: 'Pay-as-you-go Z.ai API (api/paas/v4). glm-5.2 — flagship (1M context). Lighter: glm-4.6, glm-4.5-air. NOTE: if you have a Coding Plan, pick "GLM (Z.ai) — Coding Plan" instead — this standard endpoint does NOT use your plan allowance and will hit lower rate limits.' },
  { id: 'kimi-code', label: 'Moonshot (Kimi) — Kimi Plan', baseURL: 'https://api.kimi.com/coding/v1', workerModel: 'kimi-for-coding', modelHint: 'For Kimi plan members (Moderato/Allegretto/Allegro/Vivace) — uses the plan endpoint (api.kimi.com/coding/v1), which draws on your subscription allowance. Create the API key in the Kimi Code Console (kimi.com/code/console). Models: kimi-for-coding (auto-maps to the latest backend), kimi-for-coding-highspeed (Allegretto+), k3 (Kimi K3, 1M context, Moderato+). Pick THIS if you have a Kimi plan; the platform endpoint below ignores it.' },
  { id: 'moonshot', label: 'Moonshot (Kimi) — Platform API', baseURL: 'https://api.moonshot.ai/v1', workerModel: 'kimi-k3', modelHint: 'Pay-as-you-go Moonshot platform (api.moonshot.ai/v1); key from platform.moonshot.ai. kimi-k3 — flagship open-weight (1M context). Lighter: kimi-k2.5. NOTE: if you have a Kimi plan, pick "Moonshot (Kimi) — Kimi Plan" instead — this platform endpoint does NOT use your plan allowance.' },
  { id: 'xai', label: 'xAI (Grok)', baseURL: 'https://api.x.ai/v1', workerModel: 'grok-4', modelHint: 'xAI OpenAI-compatible API (api.x.ai/v1). Key from console.x.ai. grok-4 is the current flagship; Browse models after connecting to pick grok-3 / grok-3-mini / grok-2. Use as a BYO brain or worker — not an OAuth subscription.' },
  { id: 'custom', label: 'Custom (any OpenAI-compatible)', baseURL: '', workerModel: '', modelHint: 'Any OpenAI-compatible Chat Completions endpoint.' },
];
